set vars(blkname)                            "gcd"
set vars(col_Power)                          "1"
set vars(ddm_inputs)                         "sdc_signoff_func sdc_signoff_shift"
set vars(depth)                              "4"
set vars(eda)                                "openpower"
set vars(g2module)                           "openpower"
set vars(main_script)                        "openpower.tcl"
set vars(netlist)                            "apr_finish:v01"
set vars(pagename)                           "openpower"
set vars(sdc_signoff_func)                   "v01"
set vars(sdc_signoff_shift)                  "v01"
set vars(view)                               "Exec"
