set vars(apr_finish)                         "v01"
set vars(blkname)                            "spm"
set vars(depth)                              "4"
set vars(eda)                                "openrcx"
set vars(g2module)                           "openrcx"
set vars(main_script)                        "openrcx.tcl"
set vars(memory)                             "283.2 MB"
set vars(pagename)                           "openrcx"
set vars(run,start)                          "20260928_130031"
set vars(runlog,ago)                         "00m"
set vars(runlog,date)                        "2026-09-28_13:00"
set vars(runlog,errors)                      "0"
set vars(runlog,sdate)                       "09-28"
set vars(runlog,ww)                          "40.1"
set vars(runtime)                            "02s"
set vars(view)                               "Exec"
