set vars(blkname)                            "spm"
set vars(depth)                              "5"
set vars(g2module)                           "openpv-lvs"
set vars(memory)                             "242.1 MB"
set vars(pagename)                           "lvs"
set vars(result)                             "Pass"
set vars(run,start)                          "20260928_130220"
set vars(runlog,date)                        "2026-09-28_13:02"
set vars(runlog,errors)                      "0"
set vars(runlog,sdate)                       "09-28"
set vars(runlog,ww)                          "40.1"
set vars(runtime)                            "03s"
set vars(task)                               "lvs"
set vars(view)                               "Exec"
