source $env(G2_ROOT)/tcllib/openlib/openlib.tcl
source setup.tcl
source $fvar(tech_fvar)
set blkname $fvar(blkname)

source script/util/helpers.tcl
source script/util/flow_helpers.tcl

# LEF
read_lef $fvar(tech_lef)
foreach lef $fvar(lefs) {
  read_lef $lef
}

# MMMC: corners and liberty per corner (generated by gen-openroad-task)
source ../init/mmmc.tcl

read_db apr_place/out/session.db
read_sdc -echo ../init/sdc_apr_func/sdc.tcl

################################################################
# Clock Tree Synthesis

# Clone clock tree inverters next to register loads
# so cts does not try to buffer the inverted clocks.
repair_clock_inverters

clock_tree_synthesis -root_buf $cts_buffer -buf_list $cts_buffer \
  -sink_clustering_enable \
  -sink_clustering_max_diameter $cts_cluster_diameter

# CTS leaves a long wire from the pad to the clock tree root.
repair_clock_nets

# place clock buffers
detailed_placement

g2_openroad_rpt
g2_openroad_out


if {$fvar(sw_exit) eq "1"} {
  exit
}
