set vars(blkname)                            "spm"
set vars(depth)                              "5"
set vars(g2module)                           "openpv-gdsmerge"
set vars(memory)                             "50.2 MB"
set vars(pagename)                           "gdsmerge"
set vars(run,start)                          "20260928_130214"
set vars(runlog,date)                        "2026-09-28_13:02"
set vars(runlog,errors)                      "0"
set vars(runlog,sdate)                       "09-28"
set vars(runlog,ww)                          "40.1"
set vars(runtime)                            "02s"
set vars(task)                               "gdsmerge"
set vars(view)                               "Exec"
