set vars(blkname)                            "spm"
set vars(depth)                              "5"
set vars(g2module)                           "openpv-layout"
set vars(memory)                             "568.3 MB"
set vars(pagename)                           "layout"
set vars(run,start)                          "20260928_130147"
set vars(runlog,date)                        "2026-09-28_13:02"
set vars(runlog,errors)                      "0"
set vars(runlog,sdate)                       "09-28"
set vars(runlog,ww)                          "40.1"
set vars(runtime)                            "22s"
set vars(task)                               "layout"
set vars(view)                               "Exec"
