set vars(WxH)                                "600umx600um"
set vars(blkname)                            "gcd"
set vars(depth)                              "3"
set vars(g2module)                           "spec-blk"
set vars(inst_count)                         "300"
set vars(level)                              "0"
set vars(lim/mem)                            "{fakeram45_1024x32 : v01} {fakeram45_256x16 : v01}"
set vars(lim/stdcell)                        "{sky130_fd_sc_hd : v0.0.2} {sky130_fd_sc_hdll : v0.0.2}"
set vars(main_clock)                         "clk"
set vars(pagename)                           "gcd"
set vars(speed)                              "1000MHz"
set vars(view)                               "PPA"
