set vars(blkname)                            "spm"
set vars(depth)                              "5"
set vars(g2module)                           "openpv-drc"
set vars(memory)                             "39.9 MB"
set vars(pagename)                           "drc"
set vars(result)                             "0"
set vars(run,start)                          "20260928_130217"
set vars(runlog,date)                        "2026-09-28_13:02"
set vars(runlog,errors)                      "0"
set vars(runlog,sdate)                       "09-28"
set vars(runlog,ww)                          "40.1"
set vars(runtime)                            "01s"
set vars(task)                               "drc"
set vars(view)                               "Exec"
